require("core.plugin_config.mason")
require("core.plugin_config.autopairs")
require("core.plugin_config.barbar")
require("core.plugin_config.cmp")
require("core.plugin_config.colorscheme")
require("core.plugin_config.comment")
-- require("core.plugin_config.copilot")
require("core.plugin_config.gitsigns")
require("core.plugin_config.hlslens")
require("core.plugin_config.hop")
require("core.plugin_config.lazygit")
require("core.plugin_config.lsp")
require("core.plugin_config.lualine")
require("core.plugin_config.notify")
require("core.plugin_config.nvimtree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.mundo")
-- require("core.plugin_config.wilder")
